export default (syntax) => ({
   name: 'Nebulator',
   type: 'dark',
   colors: {
      // ---------------------------
      // Editor Base Colors
      // ---------------------------
      'selection.background': '#a855f7',
      descriptionForeground: '#9ca3af',
      errorForeground: '#f87171',
      'widget.shadow': '#00000044',
      'editor.background': '#111827',
      'editor.foreground': '#d1d5db',
      'editorLineNumber.foreground': '#374151',
      'editorLineNumber.activeForeground': '#c084fc',
      'editorCursor.foreground': '#c084fc',
      // ---------------------------
      // Badge
      // ---------------------------
      'badge.background': '#a855f7',
      'badge.foreground': '#ffffff',
      // ---------------------------
      // Activity Bar
      // ---------------------------
      'activityBar.background': '#030712',
      'activityBar.dropBackground': '#9ca3af65',
      'activityBar.foreground': '#c084fc',
      'activityBar.inactiveForeground': '#c084fc77',
      'activityBar.border': '#1f2937',
      'activityBarBadge.background': '#a855f7',
      'activityBarBadge.foreground': '#ffffff',
      'activityBar.activeBackground': '#a855f733',
      'activityBar.activeBorder': '#c084fc',
      // ---------------------------
      // Sidebar
      // ---------------------------
      'sideBar.background': '#030712',
      'sideBar.foreground': '#9ca3af',
      'sideBar.border': '#1f2937',
      'sideBar.dropBackground': '#030712',
      'sideBarTitle.foreground': '#9ca3af',
      'sideBarSectionHeader.background': '#111827',
      'sideBarSectionHeader.foreground': '#d1d5db',
      'sideBarSectionHeader.border': '#1f2937',
      // ---------------------------
      // Status Bar
      // ---------------------------
      'statusBar.background': '#030712',
      'statusBar.foreground': '#9ca3af',
      'statusBar.border': '#1f2937',
      'statusBar.debuggingBackground': '#030712',
      'statusBar.debuggingForeground': '#facc15',
      'statusBar.debuggingBorder': '#facc15af',
      'statusBar.noFolderForeground': '#d1d5db',
      'statusBar.noFolderBackground': '#030712',
      'statusBar.noFolderBorder': '#030712',
      'statusBarItem.activeBackground': '#a855f745',
      'statusBarItem.hoverBackground': '#111827',
      'statusBarItem.prominentBackground': '#111827',
      'statusBarItem.prominentHoverBackground': '#1f2937',
      // ---------------------------
      // Button
      // ---------------------------
      'button.background': '#9333ea',
      'button.foreground': '#ffffff',
      'button.hoverBackground': '#a855f7',
      // ---------------------------
      // Dropdown
      // ---------------------------
      'dropdown.background': '#111827',
      'dropdown.border': '#374151',
      'dropdown.foreground': '#d1d5db',
      // ---------------------------
      // Editor Marker Navigation
      // ---------------------------
      'editorMarkerNavigation.background': '#1f2937',
      'editorMarkerNavigationError.background': '#f87171',
      'editorMarkerNavigationWarning.background': '#facc15',
      // ---------------------------
      // Errors and warnings
      // ---------------------------
      'editorError.border': '#111827',
      'editorError.foreground': '#f87171',
      'editorWarning.border': '#111827',
      'editorWarning.foreground': '#facc15',
      'editorInfo.border': '#111827',
      'editorInfo.foreground': '#60a5fa',
      'editorHint.border': '#4ade8000',
      'editorHint.foreground': '#4ade80',
      // ---------------------------
      // Editor Groups and Tabs
      // ---------------------------
      'editorGroup.emptyBackground': '#37415133',
      'editorGroup.border': '#1f2937',
      'editorGroup.dropBackground': '#a855f733',
      // ---------------------------
      // Editor Group Header
      // ---------------------------
      'editorGroupHeader.noTabsBackground': '#030712',
      'editorGroupHeader.tabsBackground': '#030712',
      'editorGroupHeader.tabsBorder': '#1f2937',
      // ---------------------------
      // Editor Tabs
      // ---------------------------
      'tab.activeBackground': '#111827',
      'tab.unfocusedActiveBackground': '#0d1424',
      'tab.activeForeground': '#c084fc',
      'tab.border': '#1f2937',
      'tab.inactiveBackground': '#030712',
      'tab.inactiveForeground': '#6b7280',
      'tab.unfocusedActiveForeground': '#6b7280',
      'tab.unfocusedInactiveForeground': '#6b7280',
      'tab.activeBorderTop': '#c084fc',
      'tab.activeModifiedBorder': '#4ade80',
      'tab.activeBorder': '#111827',
      'tab.unfocusedActiveBorder': '#030712',
      'tab.unfocusedHoverBackground': '#c084fc21',
      // ---------------------------
      // Text Colors
      // ---------------------------
      'textBlockQuote.background': '#111827',
      'textBlockQuote.border': '#a855f7',
      'textCodeBlock.background': '#111827',
      'textLink.activeForeground': '#d8b4fe',
      'textLink.foreground': '#c084fc',
      'textPreformat.foreground': '#d8b4fe',
      'textSeparator.foreground': '#1f2937',
      // ---------------------------
      // Welcome Page
      // ---------------------------
      'walkThrough.embeddedEditorBackground': '#030712',
      'welcomePage.buttonBackground': '#111827',
      'welcomePage.buttonHoverBackground': '#1f2937',
      // ---------------------------
      // Input Control
      // ---------------------------
      'input.background': '#111827',
      'input.border': '#374151',
      'input.foreground': '#d1d5db',
      'input.placeholderForeground': '#6b7280',
      'inputOption.activeBorder': '#a855f7',
      'inputValidation.errorForeground': '#f87171',
      'inputValidation.errorBackground': '#fb2c3633',
      'inputValidation.errorBorder': '#f87171',
      'inputValidation.infoForeground': '#60a5fa',
      'inputValidation.infoBackground': '#60a5fa33',
      'inputValidation.infoBorder': '#60a5fa',
      'inputValidation.warningForeground': '#facc15',
      'inputValidation.warningBackground': '#edb20033',
      'inputValidation.warningBorder': '#facc15',
      // ---------------------------
      // Editor Widgets
      // ---------------------------
      'editorWidget.background': '#111827',
      'editorWidget.border': '#1f2937',
      'editorHoverWidget.background': '#111827',
      'editorHoverWidget.border': '#1f2937',
      'editorSuggestWidget.background': '#111827',
      'editorSuggestWidget.border': '#1f2937',
      'editorSuggestWidget.foreground': '#9ca3af',
      'editorSuggestWidget.highlightForeground': '#c084fc',
      'editorSuggestWidget.selectedBackground': '#1f2937',
      // ---------------------------
      // Gutter
      // ---------------------------
      'editorGutter.background': '#111827',
      'editorGutter.addedBackground': '#4ade80',
      'editorGutter.deletedBackground': '#f87171',
      'editorGutter.modifiedBackground': '#facc15',
      // ---------------------------
      // Selection Colors
      // ---------------------------
      'editor.selectionBackground': '#a855f744',
      'editor.selectionHighlightBackground': '#c084fc33',
      'editor.inactiveSelectionBackground': '#a855f733',
      'editor.wordHighlightStrongBackground': '#facc1544',
      'editor.wordHighlightBackground': '#facc1533',
      'editor.findMatchBackground': '#edb20044',
      'editor.findMatchHighlightBackground': '#a855f73d',
      'editor.findRangeHighlightBackground': '#4ade8033',
      'editor.hoverHighlightBackground': '#a855f73f',
      'editor.lineHighlightBackground': '#1f2937',
      'editor.lineHighlightBorder': '#1f2937',
      'editor.rangeHighlightBackground': '#1f2937a1',
      'editorLink.activeForeground': '#60a5fa',
      'editorWhitespace.foreground': '#ffffff21',
      'editorIndentGuide.background': '#1f2937',
      'editorIndentGuide.activeBackground': '#374151',
      'editorBracketMatch.background': '#c084fc22',
      'editorBracketMatch.border': '#c084fc',
      'editorRuler.foreground': '#1f2937',
      // ---------------------------
      // Code Lens
      // ---------------------------
      'editorCodeLens.foreground': '#6b7280',
      // ---------------------------
      // Integrated Terminal Colors
      // ---------------------------
      'terminal.ansiBlack': '#1f2937',
      'terminal.ansiRed': '#f87171',
      'terminal.ansiGreen': '#4ade80',
      'terminal.ansiYellow': '#facc15',
      'terminal.ansiBlue': '#60a5fa',
      'terminal.ansiMagenta': '#c084fc',
      'terminal.ansiCyan': '#22d3ee',
      'terminal.ansiWhite': '#d1d5db',
      'terminal.ansiBrightBlack': '#374151',
      'terminal.ansiBrightRed': '#fb2c36',
      'terminal.ansiBrightGreen': '#00c758',
      'terminal.ansiBrightYellow': '#edb200',
      'terminal.ansiBrightBlue': '#7dd3fc',
      'terminal.ansiBrightMagenta': '#d8b4fe',
      'terminal.ansiBrightCyan': '#67e8f9',
      'terminal.ansiBrightWhite': '#f3f4f6',
      'terminal.background': '#030712',
      'terminal.foreground': '#d1d5db',
      'terminalCursor.background': '#030712',
      'terminalCursor.foreground': '#d1d5db',
      // ---------------------------
      // Merge Conflicts
      // ---------------------------
      'merge.border': '#03071200',
      'merge.currentContentBackground': '#60a5fa22',
      'merge.currentHeaderBackground': '#60a5fa44',
      'merge.incomingContentBackground': '#a855f722',
      'merge.incomingHeaderBackground': '#a855f744',
      'merge.commonContentBackground': '#facc1522',
      'merge.commonHeaderBackground': '#facc1544',
      'editorOverviewRuler.currentContentForeground': '#60a5fa44',
      'editorOverviewRuler.incomingContentForeground': '#a855f744',
      'editorOverviewRuler.commonContentForeground': '#facc1544',
      'editorOverviewRuler.border': '#111827',
      // ---------------------------
      // Notification Colors
      // ---------------------------
      'notificationCenter.border': '#1f2937',
      'notificationCenterHeader.foreground': '#9ca3af',
      'notificationCenterHeader.background': '#111827',
      'notificationToast.border': '#1f2937',
      'notifications.foreground': '#d1d5db',
      'notifications.background': '#111827',
      'notifications.border': '#1f2937',
      'notificationLink.foreground': '#c084fc',
      // ---------------------------
      // Diff
      // ---------------------------
      'diffEditor.insertedTextBackground': '#00c75827',
      'diffEditor.removedTextBackground': '#f8717141',
      // ---------------------------
      // Debug
      // ---------------------------
      'debugToolBar.background': '#111827',
      'debugExceptionWidget.background': '#111827',
      'debugExceptionWidget.border': '#f87171',
      // ---------------------------
      // Extensions
      // ---------------------------
      'extensionButton.prominentBackground': '#9333ea',
      'extensionButton.prominentForeground': '#ffffff',
      'extensionButton.prominentHoverBackground': '#a855f7',
      focusBorder: '#a855f7',
      foreground: '#d1d5db',
      // ---------------------------
      // Panel
      // ---------------------------
      'panel.background': '#030712',
      'panel.border': '#374151',
      'panelTitle.activeBorder': '#a855f7',
      'panelTitle.activeForeground': '#c084fc',
      'panelTitle.inactiveForeground': '#9ca3af',
      // ---------------------------
      // Peek View Colors
      // ---------------------------
      'peekView.border': '#a855f7',
      'peekViewEditor.background': '#030712',
      'peekViewEditor.matchHighlightBackground': '#a855f779',
      'peekViewEditor.matchHighlightBorder': '#a855f7cc',
      'peekViewEditorGutter.background': '#030712',
      'peekViewResult.background': '#030712',
      'peekViewResult.fileForeground': '#d1d5db',
      'peekViewResult.lineForeground': '#9ca3af',
      'peekViewResult.matchHighlightBackground': '#1f2937',
      'peekViewResult.selectionBackground': '#1f2937',
      'peekViewResult.selectionForeground': '#d1d5db',
      'peekViewTitle.background': '#030712',
      'peekViewTitleDescription.foreground': '#9ca3af',
      'peekViewTitleLabel.foreground': '#c084fc',
      // ---------------------------
      // Progress Bar
      // ---------------------------
      'progressBar.background': '#a855f7',
      // ---------------------------
      // Scroll Bar
      // ---------------------------
      'scrollbar.shadow': '#00000044',
      'scrollbarSlider.activeBackground': '#a855f7ad',
      'scrollbarSlider.background': '#37415188',
      'scrollbarSlider.hoverBackground': '#a855f762',
      // ---------------------------
      // Git status colors in File Explorer
      // ---------------------------
      'gitDecoration.addedResourceForeground': '#00c758',
      'gitDecoration.modifiedResourceForeground': '#4ade80',
      'gitDecoration.deletedResourceForeground': '#f87171',
      'gitDecoration.untrackedResourceForeground': '#c084fc',
      'gitDecoration.ignoredResourceForeground': '#6b7280',
      'gitDecoration.conflictingResourceForeground': '#facc15',
      // ---------------------------
      // Quick Picker
      // ---------------------------
      'pickerGroup.border': '#374151',
      'pickerGroup.foreground': '#c084fc',
      // ---------------------------
      // Lists and Trees
      // ---------------------------
      'list.activeSelectionBackground': '#1f2937',
      'list.activeSelectionForeground': '#f3f4f6',
      'list.dropBackground': '#1f2937',
      'list.focusBackground': '#1f2937',
      'list.focusForeground': '#f3f4f6',
      'list.highlightForeground': '#c084fc',
      'list.hoverBackground': '#1f2937',
      'list.hoverForeground': '#f3f4f6',
      'list.inactiveFocusBackground': '#111827',
      'list.inactiveSelectionBackground': '#1f2937',
      'list.inactiveSelectionForeground': '#d1d5db',
      'list.errorForeground': '#f87171',
      'list.warningForeground': '#facc15',
      'listFilterWidget.background': '#1f2937',
      'listFilterWidget.outline': '#4ade80',
      'listFilterWidget.noMatchesOutline': '#f87171',
      'tree.indentGuidesStroke': '#374151',

      // ---------------------------
      // Settings Editor Colors
      // ---------------------------
      'settings.headerForeground': '#d1d5db',
      'settings.modifiedItemIndicator': '#4ade80',
      'settings.dropdownListBorder': '#37415188',
      'settings.dropdownBackground': '#111827',
      'settings.dropdownForeground': '#d1d5db',
      'settings.dropdownBorder': '#374151',
      'settings.checkboxBackground': '#111827',
      'settings.checkboxForeground': '#c084fc',
      'settings.checkboxBorder': '#374151',
      'settings.textInputBackground': '#111827',
      'settings.textInputForeground': '#d1d5db',
      'settings.textInputBorder': '#374151',
      'settings.numberInputBackground': '#111827',
      'settings.numberInputForeground': '#edb200',
      'settings.numberInputBorder': '#374151',
      // ---------------------------
      // Breadcrumbs
      // ---------------------------
      'breadcrumb.foreground': '#9ca3af',
      'breadcrumb.background': '#111827',
      'breadcrumb.focusForeground': '#c084fc',
      'breadcrumb.activeSelectionForeground': '#f3f4f6',
      'breadcrumbPicker.background': '#111827',
      // ---------------------------
      // Title bar
      // Note: These colors are currently only supported on macOS.
      // ---------------------------
      'titleBar.activeBackground': '#030712',
      'titleBar.activeForeground': '#d1d5db',
      'titleBar.inactiveBackground': '#030712',
      'titleBar.inactiveForeground': '#9ca3af',
      // ---------------------------
      // Custom title bar and menus
      // Note: These colors are currently only supported on Windows and Linux.
      // ---------------------------
      'menu.background': '#111827',
      'menu.foreground': '#d1d5db',
      'menu.selectionBackground': '#1f2937',
      'menu.selectionForeground': '#f3f4f6',
      'menu.selectionBorder': '#1f2937',
      'menu.separatorBackground': '#374151',
      'menubar.selectionBackground': '#1f2937',
      'menubar.selectionForeground': '#c084fc',
      'menubar.selectionBorder': '#1f2937',
      // ---------------------------
      // Snippets
      // ---------------------------
      'editor.snippetTabstopHighlightBackground': '#030712',
      'editor.snippetTabstopHighlightBorder': '#1f2937',
      'editor.snippetFinalTabstopHighlightBackground': '#030712',
      'editor.snippetFinalTabstopHighlightBorder': '#1f2937',
      // ---------------------------
      // Minimap
      // ---------------------------
      'minimap.findMatchHighlight': '#c084fcee',
      'minimap.errorHighlight': '#f87171ee',
      'minimap.warningHighlight': '#facc15ee',
      'minimapGutter.addedBackground': '#4ade80',
      'minimapGutter.modifiedBackground': '#facc15',
      'minimapGutter.deletedBackground': '#f87171',
      'minimap.background': '#11182799',
   },
   tokenColors: syntax,
});
