export default (syntax) => ({
   name: 'Nebula Light',
   type: 'light',
   colors: {
      // ---------------------------
      // Editor Base Colors
      // ---------------------------
      'selection.background': '#7c3aed',
      descriptionForeground: '#6b7280',
      errorForeground: '#dc2626',
      'widget.shadow': '#00000022',
      'editor.background': '#ffffff',
      'editor.foreground': '#374151',
      'editorLineNumber.foreground': '#d1d5db',
      'editorLineNumber.activeForeground': '#7c3aed',
      'editorCursor.foreground': '#7c3aed',
      // ---------------------------
      // Badge
      // ---------------------------
      'badge.background': '#7c3aed',
      'badge.foreground': '#ffffff',
      // ---------------------------
      // Activity Bar
      // ---------------------------
      'activityBar.background': '#f3f4f6',
      'activityBar.dropBackground': '#6b728065',
      'activityBar.foreground': '#7c3aed',
      'activityBar.inactiveForeground': '#7c3aed77',
      'activityBar.border': '#e5e7eb',
      'activityBarBadge.background': '#7c3aed',
      'activityBarBadge.foreground': '#ffffff',
      'activityBar.activeBackground': '#7c3aed14',
      'activityBar.activeBorder': '#7c3aed',
      // ---------------------------
      // Sidebar
      // ---------------------------
      'sideBar.background': '#f3f4f6',
      'sideBar.foreground': '#6b7280',
      'sideBar.border': '#e5e7eb',
      'sideBar.dropBackground': '#f3f4f6',
      'sideBarTitle.foreground': '#6b7280',
      'sideBarSectionHeader.background': '#ffffff',
      'sideBarSectionHeader.foreground': '#374151',
      'sideBarSectionHeader.border': '#e5e7eb',
      // ---------------------------
      // Status Bar
      // ---------------------------
      'statusBar.background': '#f3f4f6',
      'statusBar.foreground': '#6b7280',
      'statusBar.border': '#e5e7eb',
      'statusBar.debuggingBackground': '#f3f4f6',
      'statusBar.debuggingForeground': '#ca8a04',
      'statusBar.debuggingBorder': '#ca8a04af',
      'statusBar.noFolderForeground': '#374151',
      'statusBar.noFolderBackground': '#f3f4f6',
      'statusBar.noFolderBorder': '#f3f4f6',
      'statusBarItem.activeBackground': '#7c3aed22',
      'statusBarItem.hoverBackground': '#e5e7eb',
      'statusBarItem.prominentBackground': '#e5e7eb',
      'statusBarItem.prominentHoverBackground': '#d1d5db',
      // ---------------------------
      // Button
      // ---------------------------
      'button.background': '#9333ea',
      'button.foreground': '#ffffff',
      'button.hoverBackground': '#7c3aed',
      // ---------------------------
      // Dropdown
      // ---------------------------
      'dropdown.background': '#ffffff',
      'dropdown.border': '#d1d5db',
      'dropdown.foreground': '#374151',
      // ---------------------------
      // Editor Marker Navigation
      // ---------------------------
      'editorMarkerNavigation.background': '#e5e7eb',
      'editorMarkerNavigationError.background': '#dc2626',
      'editorMarkerNavigationWarning.background': '#ca8a04',
      // ---------------------------
      // Errors and warnings
      // ---------------------------
      'editorError.border': '#ffffff',
      'editorError.foreground': '#dc2626',
      'editorWarning.border': '#ffffff',
      'editorWarning.foreground': '#ca8a04',
      'editorInfo.border': '#ffffff',
      'editorInfo.foreground': '#2563eb',
      'editorHint.border': '#16a34a00',
      'editorHint.foreground': '#16a34a',
      // ---------------------------
      // Editor Groups and Tabs
      // ---------------------------
      'editorGroup.emptyBackground': '#d1d5db33',
      'editorGroup.border': '#e5e7eb',
      'editorGroup.dropBackground': '#7c3aed22',
      // ---------------------------
      // Editor Group Header
      // ---------------------------
      'editorGroupHeader.noTabsBackground': '#f3f4f6',
      'editorGroupHeader.tabsBackground': '#f3f4f6',
      'editorGroupHeader.tabsBorder': '#e5e7eb',
      // ---------------------------
      // Editor Tabs
      // ---------------------------
      'tab.activeBackground': '#ffffff',
      'tab.unfocusedActiveBackground': '#f9fafb',
      'tab.activeForeground': '#7c3aed',
      'tab.border': '#e5e7eb',
      'tab.inactiveBackground': '#f3f4f6',
      'tab.inactiveForeground': '#9ca3af',
      'tab.unfocusedActiveForeground': '#9ca3af',
      'tab.unfocusedInactiveForeground': '#9ca3af',
      'tab.activeBorderTop': '#7c3aed',
      'tab.activeModifiedBorder': '#16a34a',
      'tab.activeBorder': '#ffffff',
      'tab.unfocusedActiveBorder': '#f3f4f6',
      'tab.unfocusedHoverBackground': '#7c3aed14',
      // ---------------------------
      // Text Colors
      // ---------------------------
      'textBlockQuote.background': '#f3f4f6',
      'textBlockQuote.border': '#a855f7',
      'textCodeBlock.background': '#f3f4f6',
      'textLink.activeForeground': '#9333ea',
      'textLink.foreground': '#7c3aed',
      'textPreformat.foreground': '#7c3aed',
      'textSeparator.foreground': '#e5e7eb',
      // ---------------------------
      // Welcome Page
      // ---------------------------
      'walkThrough.embeddedEditorBackground': '#f3f4f6',
      'welcomePage.buttonBackground': '#f3f4f6',
      'welcomePage.buttonHoverBackground': '#e5e7eb',
      // ---------------------------
      // Input Control
      // ---------------------------
      'input.background': '#ffffff',
      'input.border': '#d1d5db',
      'input.foreground': '#374151',
      'input.placeholderForeground': '#9ca3af',
      'inputOption.activeBorder': '#7c3aed',
      'inputValidation.errorForeground': '#dc2626',
      'inputValidation.errorBackground': '#fb2c3614',
      'inputValidation.errorBorder': '#dc2626',
      'inputValidation.infoForeground': '#2563eb',
      'inputValidation.infoBackground': '#2563eb14',
      'inputValidation.infoBorder': '#2563eb',
      'inputValidation.warningForeground': '#ca8a04',
      'inputValidation.warningBackground': '#edb20014',
      'inputValidation.warningBorder': '#ca8a04',
      // ---------------------------
      // Editor Widgets
      // ---------------------------
      'editorWidget.background': '#ffffff',
      'editorWidget.border': '#e5e7eb',
      'editorHoverWidget.background': '#ffffff',
      'editorHoverWidget.border': '#e5e7eb',
      'editorSuggestWidget.background': '#ffffff',
      'editorSuggestWidget.border': '#e5e7eb',
      'editorSuggestWidget.foreground': '#6b7280',
      'editorSuggestWidget.highlightForeground': '#7c3aed',
      'editorSuggestWidget.selectedBackground': '#f3f4f6',
      // ---------------------------
      // Gutter
      // ---------------------------
      'editorGutter.background': '#ffffff',
      'editorGutter.addedBackground': '#16a34a',
      'editorGutter.deletedBackground': '#dc2626',
      'editorGutter.modifiedBackground': '#ca8a04',
      // ---------------------------
      // Selection Colors
      // ---------------------------
      'editor.selectionBackground': '#a855f744',
      'editor.selectionHighlightBackground': '#a855f722',
      'editor.inactiveSelectionBackground': '#a855f722',
      'editor.wordHighlightStrongBackground': '#ca8a0433',
      'editor.wordHighlightBackground': '#ca8a0422',
      'editor.findMatchBackground': '#edb20044',
      'editor.findMatchHighlightBackground': '#a855f72a',
      'editor.findRangeHighlightBackground': '#16a34a22',
      'editor.hoverHighlightBackground': '#a855f72a',
      'editor.lineHighlightBackground': '#f3f4f6',
      'editor.lineHighlightBorder': '#f3f4f6',
      'editor.rangeHighlightBackground': '#f3f4f6a1',
      'editorLink.activeForeground': '#2563eb',
      'editorWhitespace.foreground': '#00000021',
      'editorIndentGuide.background': '#e5e7eb',
      'editorIndentGuide.activeBackground': '#d1d5db',
      'editorBracketMatch.background': '#7c3aed1a',
      'editorBracketMatch.border': '#7c3aed',
      'editorRuler.foreground': '#e5e7eb',
      // ---------------------------
      // Code Lens
      // ---------------------------
      'editorCodeLens.foreground': '#9ca3af',
      // ---------------------------
      // Integrated Terminal Colors
      // ---------------------------
      'terminal.ansiBlack': '#e5e7eb',
      'terminal.ansiRed': '#dc2626',
      'terminal.ansiGreen': '#16a34a',
      'terminal.ansiYellow': '#ca8a04',
      'terminal.ansiBlue': '#2563eb',
      'terminal.ansiMagenta': '#9333ea',
      'terminal.ansiCyan': '#0e7490',
      'terminal.ansiWhite': '#374151',
      'terminal.ansiBrightBlack': '#d1d5db',
      'terminal.ansiBrightRed': '#b91c1c',
      'terminal.ansiBrightGreen': '#15803d',
      'terminal.ansiBrightYellow': '#a16207',
      'terminal.ansiBrightBlue': '#1d4ed8',
      'terminal.ansiBrightMagenta': '#7c3aed',
      'terminal.ansiBrightCyan': '#155e75',
      'terminal.ansiBrightWhite': '#111827',
      'terminal.background': '#ffffff',
      'terminal.foreground': '#374151',
      'terminalCursor.background': '#ffffff',
      'terminalCursor.foreground': '#374151',
      // ---------------------------
      // Merge Conflicts
      // ---------------------------
      'merge.border': '#ffffff00',
      'merge.currentContentBackground': '#2563eb1a',
      'merge.currentHeaderBackground': '#2563eb33',
      'merge.incomingContentBackground': '#a855f71a',
      'merge.incomingHeaderBackground': '#a855f733',
      'merge.commonContentBackground': '#ca8a041a',
      'merge.commonHeaderBackground': '#ca8a0433',
      'editorOverviewRuler.currentContentForeground': '#2563eb33',
      'editorOverviewRuler.incomingContentForeground': '#a855f733',
      'editorOverviewRuler.commonContentForeground': '#ca8a0433',
      'editorOverviewRuler.border': '#ffffff',
      // ---------------------------
      // Notification Colors
      // ---------------------------
      'notificationCenter.border': '#e5e7eb',
      'notificationCenterHeader.foreground': '#6b7280',
      'notificationCenterHeader.background': '#ffffff',
      'notificationToast.border': '#e5e7eb',
      'notifications.foreground': '#374151',
      'notifications.background': '#ffffff',
      'notifications.border': '#e5e7eb',
      'notificationLink.foreground': '#7c3aed',
      // ---------------------------
      // Diff
      // ---------------------------
      'diffEditor.insertedTextBackground': '#16a34a1a',
      'diffEditor.removedTextBackground': '#dc262622',
      // ---------------------------
      // Debug
      // ---------------------------
      'debugToolBar.background': '#ffffff',
      'debugExceptionWidget.background': '#ffffff',
      'debugExceptionWidget.border': '#dc2626',
      // ---------------------------
      // Extensions
      // ---------------------------
      'extensionButton.prominentBackground': '#9333ea',
      'extensionButton.prominentForeground': '#ffffff',
      'extensionButton.prominentHoverBackground': '#7c3aed',
      focusBorder: '#a855f7',
      foreground: '#374151',
      // ---------------------------
      // Panel
      // ---------------------------
      'panel.background': '#f3f4f6',
      'panel.border': '#d1d5db',
      'panelTitle.activeBorder': '#a855f7',
      'panelTitle.activeForeground': '#7c3aed',
      'panelTitle.inactiveForeground': '#6b7280',
      // ---------------------------
      // Peek View Colors
      // ---------------------------
      'peekView.border': '#a855f7',
      'peekViewEditor.background': '#f9fafb',
      'peekViewEditor.matchHighlightBackground': '#a855f73d',
      'peekViewEditor.matchHighlightBorder': '#a855f766',
      'peekViewEditorGutter.background': '#f9fafb',
      'peekViewResult.background': '#f9fafb',
      'peekViewResult.fileForeground': '#374151',
      'peekViewResult.lineForeground': '#6b7280',
      'peekViewResult.matchHighlightBackground': '#e5e7eb',
      'peekViewResult.selectionBackground': '#e5e7eb',
      'peekViewResult.selectionForeground': '#374151',
      'peekViewTitle.background': '#f9fafb',
      'peekViewTitleDescription.foreground': '#6b7280',
      'peekViewTitleLabel.foreground': '#7c3aed',
      // ---------------------------
      // Progress Bar
      // ---------------------------
      'progressBar.background': '#a855f7',
      // ---------------------------
      // Scroll Bar
      // ---------------------------
      'scrollbar.shadow': '#00000022',
      'scrollbarSlider.activeBackground': '#a855f7ad',
      'scrollbarSlider.background': '#4b556388',
      'scrollbarSlider.hoverBackground': '#a855f762',
      // ---------------------------
      // Git status colors in File Explorer
      // ---------------------------
      'gitDecoration.addedResourceForeground': '#15803d',
      'gitDecoration.modifiedResourceForeground': '#16a34a',
      'gitDecoration.deletedResourceForeground': '#dc2626',
      'gitDecoration.untrackedResourceForeground': '#7c3aed',
      'gitDecoration.ignoredResourceForeground': '#9ca3af',
      'gitDecoration.conflictingResourceForeground': '#ca8a04',
      // ---------------------------
      // Quick Picker
      // ---------------------------
      'pickerGroup.border': '#d1d5db',
      'pickerGroup.foreground': '#7c3aed',
      // ---------------------------
      // Lists and Trees
      // ---------------------------
      'list.activeSelectionBackground': '#e5e7eb',
      'list.activeSelectionForeground': '#111827',
      'list.dropBackground': '#e5e7eb',
      'list.focusBackground': '#e5e7eb',
      'list.focusForeground': '#111827',
      'list.highlightForeground': '#7c3aed',
      'list.hoverBackground': '#f3f4f6',
      'list.hoverForeground': '#111827',
      'list.inactiveFocusBackground': '#f3f4f6',
      'list.inactiveSelectionBackground': '#e5e7eb',
      'list.inactiveSelectionForeground': '#374151',
      'list.errorForeground': '#dc2626',
      'list.warningForeground': '#ca8a04',
      'listFilterWidget.background': '#e5e7eb',
      'listFilterWidget.outline': '#16a34a',
      'listFilterWidget.noMatchesOutline': '#dc2626',
      'tree.indentGuidesStroke': '#d1d5db',

      // ---------------------------
      // Settings Editor Colors
      // ---------------------------
      'settings.headerForeground': '#374151',
      'settings.modifiedItemIndicator': '#16a34a',
      'settings.dropdownListBorder': '#d1d5db88',
      'settings.dropdownBackground': '#ffffff',
      'settings.dropdownForeground': '#374151',
      'settings.dropdownBorder': '#d1d5db',
      'settings.checkboxBackground': '#ffffff',
      'settings.checkboxForeground': '#7c3aed',
      'settings.checkboxBorder': '#d1d5db',
      'settings.textInputBackground': '#ffffff',
      'settings.textInputForeground': '#374151',
      'settings.textInputBorder': '#d1d5db',
      'settings.numberInputBackground': '#ffffff',
      'settings.numberInputForeground': '#a16207',
      'settings.numberInputBorder': '#d1d5db',
      // ---------------------------
      // Breadcrumbs
      // ---------------------------
      'breadcrumb.foreground': '#6b7280',
      'breadcrumb.background': '#ffffff',
      'breadcrumb.focusForeground': '#7c3aed',
      'breadcrumb.activeSelectionForeground': '#111827',
      'breadcrumbPicker.background': '#ffffff',
      // ---------------------------
      // Title bar
      // Note: These colors are currently only supported on macOS.
      // ---------------------------
      'titleBar.activeBackground': '#f3f4f6',
      'titleBar.activeForeground': '#374151',
      'titleBar.inactiveBackground': '#f3f4f6',
      'titleBar.inactiveForeground': '#6b7280',
      // ---------------------------
      // Custom title bar and menus
      // Note: These colors are currently only supported on Windows and Linux.
      // ---------------------------
      'menu.background': '#ffffff',
      'menu.foreground': '#374151',
      'menu.selectionBackground': '#f3f4f6',
      'menu.selectionForeground': '#7c3aed',
      'menu.selectionBorder': '#f3f4f6',
      'menu.separatorBackground': '#d1d5db',
      'menubar.selectionBackground': '#f3f4f6',
      'menubar.selectionForeground': '#7c3aed',
      'menubar.selectionBorder': '#f3f4f6',
      // ---------------------------
      // Snippets
      // ---------------------------
      'editor.snippetTabstopHighlightBackground': '#f3f4f6',
      'editor.snippetTabstopHighlightBorder': '#e5e7eb',
      'editor.snippetFinalTabstopHighlightBackground': '#f3f4f6',
      'editor.snippetFinalTabstopHighlightBorder': '#e5e7eb',
      // ---------------------------
      // Minimap
      // ---------------------------
      'minimap.findMatchHighlight': '#7c3aedd9',
      'minimap.errorHighlight': '#dc2626d9',
      'minimap.warningHighlight': '#ca8a04d9',
      'minimapGutter.addedBackground': '#16a34a',
      'minimapGutter.modifiedBackground': '#ca8a04',
      'minimapGutter.deletedBackground': '#dc2626',
      'minimap.background': '#ffffff99',
   },
   tokenColors: syntax,
});
